name: Build and Release

on:
  push:
    tags:
      - "v*"  # Runs only when a tag like "v1.0.1" is pushed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Archive built files (Include package.json)
        run: |
          mkdir yamlml-release
          cp -r dist/ package.json package-lock.json README.md yamlml-release/
          tar -cvzf yamlml.tar.gz -C yamlml-release .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: yamlml.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
